In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [3]:
lst = [1,2,3,4,5]
a=np.array(lst)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a.ndim

1

In [5]:
# numpy array is collection of homogenous elemnets
# Array use vectorised operation b using array broadcasting
# if we pass heterogenous element, then it converts all elements to one data type
# int < float < complex < string < object

In [6]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [7]:
arr = np.array([1,2.0,3,4,5])
arr.dtype

dtype('float64')

In [8]:
arr = np.array([1,2.0,3+9j,4,5])
arr.dtype

dtype('complex128')

In [9]:
# np.arange(start, stop, step-size)
arr= np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# np.linspace(start, stop, nu_of_values)
arr = np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

In [11]:
arr = np.zeros((3,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
arr = np.zeros(3) # arr = np.zeros((3))
arr

array([0., 0., 0.])

In [13]:
arr = np.ones((2,3),dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
# np.full((rows,columns), values)
arr = np.full((4,4),7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr = np.eye(4,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
arr = np.eye(4,3,-1)   # offset value
arr

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
br = np.array(  ([2,8,4],[54,2,9])  )

In [19]:
arr = np.zeros_like(br)  #to get array of zeros of dimensions
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
arr = np.ones_like(br)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
arr= np.full_like(br,8)
arr

array([[8, 8, 8],
       [8, 8, 8]])

In [22]:
arr = np.random.randint(10,100,36)
arr = arr.reshape(6,6)
print(arr)
z = np.diagonal(arr)
print(z)
z = np.diagonal(arr, offset=-1)
print(z)

[[80 96 59 77 62 58]
 [53 43 70 15 63 38]
 [78 35 19 53 94 76]
 [87 49 81 13 78 78]
 [58 32 88 44 14 79]
 [76 44 33 51 30 43]]
[80 43 19 13 14 43]
[53 35 81 44 30]


In [23]:
a = np.trace(arr)
a

212

## Attribute - these are characteristics or properties of an object

In [24]:
arr = np.random.random(9)
arr.shape

(9,)

In [25]:
arr1 = arr.reshape(3,3)
arr1

array([[0.83551697, 0.69940194, 0.6177601 ],
       [0.36370769, 0.70571407, 0.85831327],
       [0.34052999, 0.38459966, 0.65118158]])

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr = np.random.random(30)
arr_2 = arr.reshape(3,5,2)
arr_2

array([[[0.74492128, 0.07332893],
        [0.71825552, 0.74046938],
        [0.73191867, 0.24957523],
        [0.7405225 , 0.27801911],
        [0.31330371, 0.60334   ]],

       [[0.23952558, 0.70783386],
        [0.20093758, 0.55341798],
        [0.31195983, 0.94094785],
        [0.35337622, 0.31569427],
        [0.90700119, 0.60369978]],

       [[0.57220083, 0.52946463],
        [0.3665368 , 0.12522627],
        [0.52089393, 0.12284545],
        [0.70873018, 0.31149732],
        [0.35208974, 0.61861897]]])

In [28]:
arr_2.ndim

3

In [29]:
arr_2.dtype

dtype('float64')

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [31]:
arr[2::2]

array([3, 5, 7, 9])

In [32]:
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
arr[0]

array([10, 20, 30])

In [34]:
arr[0,1]

20

In [35]:
arr[1:,1:]

array([[50, 60],
       [80, 90]])

In [36]:
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160]).reshape(4,4)
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [37]:
arr[3:,1:4]

array([[140, 150, 160]])

In [38]:
arr = np.random.random(9).reshape(3,3)
arr

array([[0.65633202, 0.95762088, 0.7264755 ],
       [0.91529418, 0.51525332, 0.46947966],
       [0.57979776, 0.19389305, 0.55584063]])

In [39]:
arr1 = np.random.rand(3,3)
arr1

array([[0.19417439, 0.96867606, 0.46502848],
       [0.97754865, 0.38103784, 0.24104159],
       [0.37782728, 0.40657863, 0.62710604]])

In [40]:
# Generates random integers
arr2= np.random.randint(2,10,15)
arr2

array([6, 6, 4, 6, 7, 8, 8, 6, 9, 5, 7, 7, 9, 2, 3])

In [46]:
np.random.seed(10)
arr3 = np.random.randint(10,100,6)
arr3

array([19, 25, 74, 38, 99, 39])

In [47]:
arr4 = np.random.randint(10,100,6)
arr4

array([18, 83, 10, 50, 46, 26])

In [48]:
arr5 = np.random.normal(100,5,150)
arr5

array([ 97.32602736, 105.16435568,  99.31882124, 100.88186537,
       101.55425368, 108.64687942,  98.79669028,  94.86323988,
       102.12007535, 107.04310437, 102.19996008,  97.85882803,
        98.4399366 ,  97.15558307,  92.07529494, 105.27676579,
        90.36710445, 103.49291939,  96.26899285,  99.21686668,
        99.03182031, 105.69562673, 101.81108982,  97.04543507,
       101.94681522,  97.36501924,  97.42846046, 104.48804587,
       104.94626044, 101.29612566,  99.87903405, 101.79248332,
        98.11226818, 103.47815581, 105.12422324, 108.53877722,
        90.16441388,  95.64521666,  94.4658726 , 101.37561829,
        98.17771928,  94.17423265,  93.28465058, 107.2669643 ,
       100.00584724,  99.94039808, 103.57941572,  94.07115727,
        96.81836048,  96.94593078,  93.40304302,  97.19135792,
       101.02692287,  95.23319662, 101.60758976,  92.39530663,
        89.19273541, 101.72656647, 104.39484692, 102.81381503,
       101.44217668,  94.96759248, 100.2698921 ,  90.86

In [49]:
np.sum(arr5)

14942.226866859588