In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [4]:
lst = [1,2,3,4,5]
a=np.array(lst)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a.ndim

1

In [7]:
# numpy array is collection of homogenous elemnets
# Array use vectorised operation b using array broadcasting
# if we pass heterogenous element, then it converts all elements to one data type
# int < float < complex < string < object

In [8]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [9]:
arr = np.array([1,2.0,3,4,5])
arr.dtype

dtype('float64')

In [10]:
arr = np.array([1,2.0,3+9j,4,5])
arr.dtype

dtype('complex128')

In [12]:
# np.arange(start, stop, step-size)
arr= np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# np.linspace(start, stop, nu_of_values)
arr = np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

In [15]:
arr = np.zeros((3,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
arr = np.zeros(3) # arr = np.zeros((3))
arr

array([0., 0., 0.])

In [18]:
arr = np.ones((2,3),dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
# np.full((rows,columns), values)
arr = np.full((4,4),7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [21]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.eye(4,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
arr = np.eye(4,3,-1)   # offset value
arr

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
br = np.array(  ([2,8,4],[54,2,9])  )

In [30]:
arr = np.zeros_like(br)  #to get array of zeros of dimensions
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
arr = np.ones_like(br)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
arr= np.full_like(br,8)
arr

array([[8, 8, 8],
       [8, 8, 8]])

In [34]:
arr = np.random.randint(10,100,36)
arr = arr.reshape(6,6)
print(arr)
z = np.diagonal(arr)
print(z)
z = np.diagonal(arr, offset=-1)
print(z)

[[25 43 75 33 26 35]
 [52 25 85 84 68 67]
 [15 22 28 21 79 22]
 [50 43 22 13 44 74]
 [13 99 78 36 55 52]
 [64 95 63 51 62 77]]
[25 25 28 13 55 77]
[52 22 22 36 62]


In [35]:
a = np.trace(arr)
a

223

## Attribute - these are characteristics or properties of an object

In [47]:
arr = np.random.random(9)
arr.shape

(9,)

In [48]:
arr1 = arr.reshape(3,3)
arr1

array([[0.03760453, 0.64728874, 0.28413084],
       [0.40051941, 0.38261741, 0.07185505],
       [0.35554706, 0.89365946, 0.71385721]])

In [49]:
arr1.dtype

dtype('float64')

In [50]:
arr = np.random.random(30)
arr_2 = arr.reshape(3,5,2)
arr_2

array([[[0.71551626, 0.25662351],
        [0.76420744, 0.13279274],
        [0.77174505, 0.30294123],
        [0.9615782 , 0.98603587],
        [0.70784164, 0.641542  ]],

       [[0.02848834, 0.90135026],
        [0.95301599, 0.70202267],
        [0.17645147, 0.4022281 ],
        [0.40657511, 0.87961321],
        [0.58740364, 0.24419476]],

       [[0.65011339, 0.52602287],
        [0.11478733, 0.21249812],
        [0.57449792, 0.80317198],
        [0.23323707, 0.76848349],
        [0.2123562 , 0.07037269]]])

In [52]:
arr_2.ndim

3